-- AIコメント自動生成cron（api/generate-daily-comments.ts、2026年8月29日新設）が
-- 必要とするservice_role権限の調査記録。
--
-- 【2026年8月29日、調査完了・実行不要と判明】
-- 当初、cronが参照するテーブルのうちmeal_log_food_items・workoutsへの
-- service_role権限付与状況が未確認だったため、このファイルは両テーブルへの
-- SELECT権限を確認・追加するDRAFTとして作成した。
--
-- その後、Johnさんがライブクエリでdaily_conditions・meal_log_food_items・
-- workoutsの3テーブルとも既にservice_roleへ必要な権限（SELECT等）が付与済みで
-- あることを確認した。このため、このファイルが提案していたGRANT文
-- （grant select on meal_log_food_items to service_role;）は不要になった。
--
-- 【meal_sizesについて（追加調査、2026年8月29日）】
-- api/generate-daily-comments.tsのデータ取得コードを全件洗い出したところ
-- （.from('...')呼び出し全件：daily_conditions・training_logs・
-- training_log_exercises・training_sets・soccer_logs・workouts・meal_logs・
-- meal_log_food_items）、meal_sizesへの参照は無いことを確認した。
-- buildDailySummaryText（src/utils/dailyCommentHelpers.ts）はmeal_log_food_items
-- の確定スナップショット列（サイズ倍率適用後の値）を直接合算する設計のため、
-- サイズ倍率マスタであるmeal_sizes自体を参照する経路が無い。したがって
-- meal_sizesへのservice_role GRANTも不要と判断した。
--
-- 【結論】api/generate-daily-comments.tsのために新たに実行すべきGRANT文は
-- 無い。このファイルは実行不要（未実行のまま運用終了）。
